name: PIP packages
on:
  push:
    branches: [master]
env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
jobs:
  macos:
    runs-on: macos-10.15
    steps:
    - name: Install Dependencies
      run: brew update && brew install swig
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build
      run: |
        pip install setuptools wheel twine
        pip wheel . --verbose
        python -m twine upload --repository pypi *.whl